AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 15
Resources:
  ApScraper:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ap
      Handler: main.handler
      Runtime: python3.6
      Timeout: 15
      Events:
        PullApDataHourly:
          Type: Schedule
          Properties:
            Description: Pull latest data from Associated Press
            Enabled: True
            Schedule: rate(1 hour)
      Policies:
        - AWSLambdaExecute
