AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 15
Resources:
  ApScraper:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ap
      Handler: main.handler
      Runtime: python3.6
