AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Associated Press RSS Feeds
Globals:
  Function:
    Timeout: 30

Resources:
  ScrapyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: scrapy
      Description: Dependencies for scrapy
      ContentUri: dependencies/
      CompatibleRuntimes:
        - python3.6
      LicenseInfo: 'MIT'
      RetentionPolicy: Delete

  {% for item in config %}
  ApScraper{{ item['name'].replace(' ', '') }}:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ap
      Handler: main.handler
      Runtime: python3.6
      Timeout: 30
      Policies:
        - AWSLambdaExecute
      Layers:
        - Ref: ScrapyLayer
      Environment:
        Variables:
          BUCKET: associated-press
      Events:
        Pull:
          Type: Schedule
          Properties:
            Enabled: True
            Schedule: cron(0 * * * ? *)
            Description: Pull latest data from Associated Press {{ item['name'] }}
            Input: '{"url": "https://apnews.com/apf-{{ item['url'] }}","title": "AP {{ item['name'] }}"}'

  Alarm{{ item['name'].replace(' ', '') }}:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Broken Lambda for {{ item['name'].replace(' ', '') }}
      AlarmName: BrokenAPLambda{{ item['name'].replace(' ', '') }}
      # AlarmActions:
      #   - arn:aws:sns:ap-southeast-2:279458537408:my-phone
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 900
      Dimensions:
        - Name: FunctionName
          Value:
            Ref: ApScraper{{ item['name'].replace(' ', '') }}
      TreatMissingData: missing
      Threshold: 1.0
      Statistic: Sum
  {% endfor %}

